package cmd

import (
	// Keno
	_ "github.com/slotopol/server/game/keno/americankeno"
	_ "github.com/slotopol/server/game/keno/firekeno"
	_ "github.com/slotopol/server/game/keno/kenocenturion"
	_ "github.com/slotopol/server/game/keno/kenofast"
	_ "github.com/slotopol/server/game/keno/kenoluxury"

	// AGT
	_ "github.com/slotopol/server/game/slot/agt/aislot"
	_ "github.com/slotopol/server/game/slot/agt/aladdin"
	_ "github.com/slotopol/server/game/slot/agt/cherryhot"
	_ "github.com/slotopol/server/game/slot/agt/doubleice"
	_ "github.com/slotopol/server/game/slot/agt/egypt"
	_ "github.com/slotopol/server/game/slot/agt/extraspin"
	_ "github.com/slotopol/server/game/slot/agt/extraspin3"
	_ "github.com/slotopol/server/game/slot/agt/fruitqueen"
	_ "github.com/slotopol/server/game/slot/agt/gems"
	_ "github.com/slotopol/server/game/slot/agt/gems50"
	_ "github.com/slotopol/server/game/slot/agt/halloween"
	_ "github.com/slotopol/server/game/slot/agt/hotclover"
	_ "github.com/slotopol/server/game/slot/agt/icefruits"
	_ "github.com/slotopol/server/game/slot/agt/iceiceice"
	_ "github.com/slotopol/server/game/slot/agt/icequeen"
	_ "github.com/slotopol/server/game/slot/agt/infinitygems"
	_ "github.com/slotopol/server/game/slot/agt/jokers"
	_ "github.com/slotopol/server/game/slot/agt/jokers100"
	_ "github.com/slotopol/server/game/slot/agt/luckyslot"
	_ "github.com/slotopol/server/game/slot/agt/merrychristmas"
	_ "github.com/slotopol/server/game/slot/agt/panda"
	_ "github.com/slotopol/server/game/slot/agt/santa"
	_ "github.com/slotopol/server/game/slot/agt/sevenhot"
	_ "github.com/slotopol/server/game/slot/agt/shiningstars"
	_ "github.com/slotopol/server/game/slot/agt/shiningstars100"
	_ "github.com/slotopol/server/game/slot/agt/suncity"
	_ "github.com/slotopol/server/game/slot/agt/valentinesday"
	_ "github.com/slotopol/server/game/slot/agt/valkyrie"
	_ "github.com/slotopol/server/game/slot/agt/wizard"

	// Aristocrat
	_ "github.com/slotopol/server/game/slot/aristocrat/indiandreaming"
	_ "github.com/slotopol/server/game/slot/aristocrat/redroo"

	// BetSoft
	_ "github.com/slotopol/server/game/slot/betsoft/2millionbc"
	_ "github.com/slotopol/server/game/slot/betsoft/atthemovies"

	// CT Interactive
	_ "github.com/slotopol/server/game/slot/ct/britania"
	_ "github.com/slotopol/server/game/slot/ct/cloverparty"
	_ "github.com/slotopol/server/game/slot/ct/dancingbananas"
	_ "github.com/slotopol/server/game/slot/ct/doublehothabanero"
	_ "github.com/slotopol/server/game/slot/ct/fortunepyramid"
	_ "github.com/slotopol/server/game/slot/ct/fruitgalaxy"
	_ "github.com/slotopol/server/game/slot/ct/fusionfruitbeat"
	_ "github.com/slotopol/server/game/slot/ct/groovyautomat"
	_ "github.com/slotopol/server/game/slot/ct/hitthehot"
	_ "github.com/slotopol/server/game/slot/ct/sapphirelagoon"
	_ "github.com/slotopol/server/game/slot/ct/treasurehill"
	_ "github.com/slotopol/server/game/slot/ct/tropicdancer"
	_ "github.com/slotopol/server/game/slot/ct/vikingsfun"
	_ "github.com/slotopol/server/game/slot/ct/wildhills"
	_ "github.com/slotopol/server/game/slot/ct/winstorm"

	// IGT
	_ "github.com/slotopol/server/game/slot/igt/cleopatra"
	_ "github.com/slotopol/server/game/slot/igt/doublediamond"
	_ "github.com/slotopol/server/game/slot/igt/richgirl"
	_ "github.com/slotopol/server/game/slot/igt/triplediamond"
	_ "github.com/slotopol/server/game/slot/igt/wolfrun"

	// Megajack
	_ "github.com/slotopol/server/game/slot/megajack/aztecgold"
	_ "github.com/slotopol/server/game/slot/megajack/champagne"
	_ "github.com/slotopol/server/game/slot/megajack/slotopol"
	_ "github.com/slotopol/server/game/slot/megajack/slotopoldeluxe"

	// NetEnt
	_ "github.com/slotopol/server/game/slot/netent/arabiannights"
	_ "github.com/slotopol/server/game/slot/netent/diamonddogs"
	_ "github.com/slotopol/server/game/slot/netent/flowers"
	_ "github.com/slotopol/server/game/slot/netent/fruitshop"
	_ "github.com/slotopol/server/game/slot/netent/gonzosquest"
	_ "github.com/slotopol/server/game/slot/netent/groovysixties"
	_ "github.com/slotopol/server/game/slot/netent/piggyriches"
	_ "github.com/slotopol/server/game/slot/netent/reelsteal"
	_ "github.com/slotopol/server/game/slot/netent/simsalabim"
	_ "github.com/slotopol/server/game/slot/netent/spellcast"
	_ "github.com/slotopol/server/game/slot/netent/thrillspin"
	_ "github.com/slotopol/server/game/slot/netent/tikiwonders"
	_ "github.com/slotopol/server/game/slot/netent/trolls"

	// Novomatic
	_ "github.com/slotopol/server/game/slot/novomatic/africansimba"
	_ "github.com/slotopol/server/game/slot/novomatic/alwayshot"
	_ "github.com/slotopol/server/game/slot/novomatic/bananasgobahamas"
	_ "github.com/slotopol/server/game/slot/novomatic/beetlemania"
	_ "github.com/slotopol/server/game/slot/novomatic/bookofra"
	_ "github.com/slotopol/server/game/slot/novomatic/cashfarm"
	_ "github.com/slotopol/server/game/slot/novomatic/chicago"
	_ "github.com/slotopol/server/game/slot/novomatic/columbus"
	_ "github.com/slotopol/server/game/slot/novomatic/dolphinspearl"
	_ "github.com/slotopol/server/game/slot/novomatic/dragonsdeep"
	_ "github.com/slotopol/server/game/slot/novomatic/dynastyofra"
	_ "github.com/slotopol/server/game/slot/novomatic/fairyqueen"
	_ "github.com/slotopol/server/game/slot/novomatic/flamedancer"
	_ "github.com/slotopol/server/game/slot/novomatic/fruitilicious"
	_ "github.com/slotopol/server/game/slot/novomatic/fruitsensation"
	_ "github.com/slotopol/server/game/slot/novomatic/helena"
	_ "github.com/slotopol/server/game/slot/novomatic/inferno"
	_ "github.com/slotopol/server/game/slot/novomatic/jaguarmoon"
	_ "github.com/slotopol/server/game/slot/novomatic/jewels"
	_ "github.com/slotopol/server/game/slot/novomatic/jewels4all"
	_ "github.com/slotopol/server/game/slot/novomatic/justjewels"
	_ "github.com/slotopol/server/game/slot/novomatic/katana"
	_ "github.com/slotopol/server/game/slot/novomatic/kingsjester"
	_ "github.com/slotopol/server/game/slot/novomatic/lovelymermaid"
	_ "github.com/slotopol/server/game/slot/novomatic/megajoker"
	_ "github.com/slotopol/server/game/slot/novomatic/oliversbar"
	_ "github.com/slotopol/server/game/slot/novomatic/plentyofjewels20"
	_ "github.com/slotopol/server/game/slot/novomatic/plentyontwenty"
	_ "github.com/slotopol/server/game/slot/novomatic/powerstars"
	_ "github.com/slotopol/server/game/slot/novomatic/roaringforties"
	_ "github.com/slotopol/server/game/slot/novomatic/royaldynasty"
	_ "github.com/slotopol/server/game/slot/novomatic/secretelixir"
	_ "github.com/slotopol/server/game/slot/novomatic/sizzlinghot"
	_ "github.com/slotopol/server/game/slot/novomatic/ultrahot"
	_ "github.com/slotopol/server/game/slot/novomatic/ultrasevens"

	// Play'n GO
	_ "github.com/slotopol/server/game/slot/playngo/copsnrobbers"
	_ "github.com/slotopol/server/game/slot/playngo/firejoker"
	_ "github.com/slotopol/server/game/slot/playngo/fortuneteller"

	// Playtech
	_ "github.com/slotopol/server/game/slot/playtech/captainstreasure"
	_ "github.com/slotopol/server/game/slot/playtech/deserttreasure"
	_ "github.com/slotopol/server/game/slot/playtech/goldentour"
	_ "github.com/slotopol/server/game/slot/playtech/greatblue"
	_ "github.com/slotopol/server/game/slot/playtech/panthermoon"
)
